#set page(width: auto, height: auto, margin: 12pt)
#import "@preview/cetz:0.4.2": canvas, draw

#canvas({
  import draw: *
  let th = (thickness: 1.2pt)
  let td = (dash: "dashed", thickness: 1pt)
  let dot = (p) => circle(p, radius: .08, fill: black, stroke: none)
  // ---------- (a) ----------
  let O = (0, 0)
  let uy = (.906, .423)   // y' at 25 deg
  let uz = (-.423, .906)  // z' at 115 deg
  line((0 - 2.1 * uy.at(0), 0 - 2.1 * uy.at(1)), (2.7 * uy.at(0), 2.7 * uy.at(1)), stroke: th, mark: (end: ">"))
  line((0 - 1.5 * uz.at(0), 0 - 1.5 * uz.at(1)), (2.8 * uz.at(0), 2.8 * uz.at(1)), stroke: th, mark: (end: ">"))
  content((2.75, 1.4), anchor: "west", [$y'$])
  content((-1.5, 2.65), anchor: "east", [$z'$])
  let L = (-1.5, 0)
  let R = (1.5, 0)
  let M = (0, 2.35)
  line(L, R, stroke: td)
  line(O, M, stroke: td)
  line(M, L, stroke: td)
  line(M, R, stroke: td)
  line((.95, -.12), (1.05, .12), stroke: th)
  dot(L)
  dot(R)
  dot(M)
  content((-.78, .22), anchor: "center", [$a$])
  content((.85, .2), anchor: "center", [$a$])
  content((-1.12, 1.2), anchor: "east", [$2a$])
  content((-1.72, .35), anchor: "east", [$m_3$])
  content((-1.72, -.38), anchor: "east", [$m_4$])
  content((1.75, .3), anchor: "west", [$m_2$])
  content((1.75, -.35), anchor: "west", [$m_1$])
  content((.25, 2.5), anchor: "west", [$m_5$])
  content((.1, -2.5), [(a)])
  // ---------- (b) ----------
  let ox = 6.6
  line((ox - 2.7, 0), (ox + 2.8, 0), stroke: th, mark: (end: ">"))
  line((ox, -1.9), (ox, 2.9), stroke: th, mark: (end: ">"))
  content((ox + 2.9, -.4), anchor: "west", [$y'$])
  content((ox + .28, 2.7), anchor: "west", [$z'$])
  let b20 = 20deg
  let w = (calc.cos(-b20), calc.sin(-b20))
  let Rb = (ox + 1.45 * w.at(0), 1.45 * w.at(1))
  let Lb = (ox - 1.45 * w.at(0), -1.45 * w.at(1))
  let Mb = (Rb.at(0), 2.2)
  line(Lb, Rb, stroke: td)
  line((ox, 0), Mb, stroke: td)
  line(Mb, Lb, stroke: td)
  line(Mb, Rb, stroke: td)
  dot(Lb)
  dot(Rb)
  dot(Mb)
  content((ox - .95, .48), anchor: "center", [$a$])
  content((ox + .55, -.85), anchor: "center", [$a$])
  content((ox + .38, 1.3), anchor: "west", [$2a$])
  content((Lb.at(0) - .2, Lb.at(1) + .3), anchor: "east", [$m_3$])
  content((Lb.at(0) - .2, Lb.at(1) - .25), anchor: "east", [$m_4$])
  content((Rb.at(0) + .22, Rb.at(1) - .05), anchor: "west", [$m_2$])
  content((Rb.at(0) + .22, Rb.at(1) - .5), anchor: "west", [$m_1$])
  content((Mb.at(0) + .25, Mb.at(1) + .1), anchor: "west", [$m_5$])
  content((ox + .1, -2.5), [(b)])
})
