#set page(width: auto, height: auto, margin: 12pt)
#import "@preview/cetz:0.4.2": canvas, draw

#canvas({
  import draw: *
  let th = (thickness: 1pt)
  let tp = (dash: "dotted", thickness: 1pt)
  let td = (dash: "dashed", thickness: 1pt)
  let tv = (thickness: 2pt)
  // (a) polar coordinates
  let P = (1.35, 2.15)
  line((-2.6, 0), (3.4, 0), stroke: th, mark: (end: ">"))
  line((0, -2.9), (0, 3.2), stroke: th, mark: (end: ">"))
  content((3.45, -.42), anchor: "west", [$x$])
  content((-0.3, 3.0), anchor: "east", [$y$])
  line(P, (P.at(0), 0), stroke: tp)
  line((0, P.at(1)), P, stroke: tp)
  line((0, 0), P, stroke: th)
  circle(P, radius: .08, fill: black, stroke: none)
  content((0.52, 1.3), anchor: "east", [$r$])
  content((0.2, 2.4), anchor: "west", [$x$])
  content((P.at(0) + .25, 1.2), anchor: "west", [$y$])
  let a = calc.atan2(P.at(1), P.at(0))
  arc((.55, 0), radius: .55, start: 0deg, stop: a, stroke: th)
  content((0.74, 0.42), [$theta$])
  content((.2, -4.2), [(a)])
  // (b) polar unit vectors
  let ox = 7.2
  line((ox - 3.6, 0), (ox + 3.6, 0), stroke: th, mark: (end: ">"))
  line((ox, -3.4), (ox, 3.4), stroke: th, mark: (end: ">"))
  content((ox + 3.65, -.42), anchor: "west", [$x$])
  content((ox - 0.3, 3.2), anchor: "east", [$y$])
  line((ox, 0), (ox + .62, 0), stroke: tv, mark: (end: ">"))
  line((ox, 0), (ox, .62), stroke: tv, mark: (end: ">"))
  content((ox + .35, -.5), [$hat(i)$])
  content((ox - .28, .5), anchor: "east", [$hat(j)$])
  let Q = (ox + 1.5, 2.55)
  let ur = (1.5 / calc.sqrt(1.5 * 1.5 + 2.55 * 2.55), 2.55 / calc.sqrt(1.5 * 1.5 + 2.55 * 2.55))
  let ut = (0.0 - ur.at(1), ur.at(0))
  line((ox, 0), (ox + 1.78, 3.03), stroke: td)
  circle(Q, radius: .08, fill: black, stroke: none)
  line(Q, (Q.at(0) + .95 * ur.at(0), Q.at(1) + .95 * ur.at(1)), stroke: tv, mark: (end: ">"))
  line(Q, (Q.at(0) + .95 * ut.at(0), Q.at(1) + .95 * ut.at(1)), stroke: tv, mark: (end: ">"))
  content((Q.at(0) + 1.2, Q.at(1) + .55), anchor: "west", [$hat(r)$])
  content((Q.at(0) - .75, Q.at(1) + 1.15), [$hat(theta)$])
  content((ox + .2, -4.2), [(b)])
})
